app/models/db_schema.py
from app.extensions import db
from flask_login import UserMixin

class User(UserMixin, db.Model):

    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(50), unique=True)
    email = db.Column(db.String(100), unique=True)
    password = db.Column(db.String(254))
    todos = db.relationship('Todo', backref='user')

    def __repr__(self) -> str:
        
        return f'<User: "{self.username}">'

class Todo(db.Model):
    
    id = db.Column(db.Integer, primary_key=True)
    task = db.Column(db.String(100))
    label = db.Column(db.String(50))
    description = db.Column(db.Text)
    due_date = db.Column(db.String(50))
    status = db.Column(db.Boolean, default=False)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))

    def __repr__(self) -> str:
        
        return f'<Todo: "{self.task}">'

app/models/todo.py
from app.extensions import db

class User(db.Model):

    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(50), unique=True)
    email = db.Column(db.String(100), unique=True)
    password = db.Column(db.String(254))
    todos = db.relationship('Todo', backref='user')

    def __repr__(self) -> str:
        
        return f'<User: "{self.username}">'

class Todo(db.Model):
    
    id = db.Column(db.Integer, primary_key=True)
    task = db.Column(db.String(100))
    label = db.Column(db.String(50))
    description = db.Column(db.Text)
    due_date = db.Column(db.String(50))
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))

    def __repr__(self) -> str:
        
        return f'<Todo: "{self.task}">'

app/__init__.py
from flask import Flask
from config import Config

from app.extensions import db, migrate, login_manager
from app.models.db_schema import User, Todo

from app.todo import bp as todo_bp

def create_app(config_object=Config):

    app = Flask(__name__)
    app.config.from_object(config_object)

    # initialize extensions
    db.init_app(app)
    migrate.init_app(app, db)
    login_manager.init_app(app)

    # register blueprints
    app.register_blueprint(todo_bp)

    # callback to reload user object from user ID stored in the session
    @login_manager.user_loader
    def load_user(id):
        
        return User.query.get(int(id))

    return app

app/todo/__init__.py
from flask import Blueprint
from app.extensions import login_manager

bp = Blueprint('todo', __name__)

from . import routes

# set default view for login_required
login_manager.login_view = 'todo.login'
login_manager.login_message_category = "info"

app/todo/routes.py
import re
import time
from datetime import datetime
from flask import render_template, redirect, url_for, flash, request
from flask_login import login_required, login_user, logout_user, current_user
from werkzeug.security import generate_password_hash, check_password_hash

from . import bp
from app.models.db_schema import User, Todo
from app.extensions import db

@bp.route('/')
@login_required
def index():

    '''App's homepage'''

    tasks = Todo.query.filter_by(user_id=current_user.id).all()

    return render_template('index.html', current_user=current_user, user_tasks=tasks)

@bp.route('/about/')
def about():

    '''Page giving more info about the app'''

    return render_template('about.html')

@bp.route('/signup/', methods=['GET', 'POST'])
def signup():

    '''Create a new user account'''

    if request.method == 'POST':

        username = request.form.get('username')
        email = request.form.get('email')
        password_one = request.form.get('password_one')
        password_two = request.form.get('password_two')

        try:

            username_already_in_use = User.query.filter_by(username=username).first()

        except:

            pass

        if username_already_in_use:

            flash("This username is already in use. Please choose a unique username.", "error")
            return redirect(url_for('todo.signup'))

        if not re.search("(^\w+)@([a-z]+)[.]([a-z]+\S)$", email):

            flash('Your email must be in the format of "abc@def.ghi", for example: example@email.com', "error")
            return redirect(url_for('todo.signup'))

        try:

            email_already_in_use = User.query.filter_by(email=email).first()

        except:

            pass

        if email_already_in_use:

            flash("This email is already in use. Please choose a unique email.", "error")
            return redirect(url_for('todo.signup'))

        if len(password_one) < 8 or len(password_two) < 8:

            flash("The password(s) provided is too short. Minimum characters expected for a strong password is 8.", "error")
            return redirect(url_for('todo.signup'))

        if password_one != password_two:

            flash("The passwords provided do not match.", "error")
            return redirect(url_for('todo.signup'))

        new_user = User(
            username=username,
            email=email,
            password=generate_password_hash(password_one, method='sha256')
        )

        try:

            db.session.add(new_user)

        except:

            raise

        else:
            
            db.session.commit()
            flash(f'User {username} created successfully!', 'message')

            return redirect(url_for('todo.login'))

    return render_template('signup.html')

@bp.route('/login/', methods=['GET', 'POST'])
def login():

    '''Login an already registered user'''

    if request.method == 'POST':

        username = request.form.get('username')
        password = request.form.get('password')

        try:

            this_user = User.query.filter_by(username=username).first()

        except:

            flash('Please check you username and try again.', 'error')
            return redirect(url_for('todo.login'))

        else:

            if this_user == None:

                flash('Please check you username and try again.', 'error')
                return redirect(url_for('todo.login'))
            
            if not check_password_hash(this_user.password, password):

                flash('Please check you password and try again.', 'error')
                return redirect(url_for('todo.login'))

            login_user(this_user, remember=True)

            flash("Logged in successfully.", "message")
            return redirect(url_for('todo.index'))

    return render_template('login.html')

@bp.route('/logout/')
def logout():

    '''Logout user'''

    logout_user()

    flash("Logged out successfully.", "message")
    return redirect(url_for('todo.login'))

@bp.route('/add_task/', methods=['POST'])
def add_task():

    '''Add new task to db'''

    task = request.form.get('task')
    label = request.form.get('label')
    description = request.form.get('description')
    due_date = request.form.get('due_date')
    user_id = current_user.id

    new_date = datetime.strptime(str(due_date), '%Y-%m-%dT%H:%M')

    new_task = Todo(
        task=task,
        label=label,
        description=description,
        due_date=new_date.strftime('%c'),
        user_id=user_id
    )

    try:

        db.session.add(new_task)

    except:

        flash("Something went wrong.", "error")
        return redirect(url_for('todo.index'))

    else:

        db.session.commit()

        flash(f'Task {task} has been added.', 'message')
        return redirect(url_for('todo.index'))

@bp.route('/task/<task_id>/', methods=['GET', 'POST'])
def task(task_id):

    '''Open specific task'''

    try:

        specific_task = Todo.query.get(int(task_id))

    except:

        flash("Something went wrong.", "error")
        return redirect(url_for('todo.index'))

    if request.method == 'POST':

        complete_boolean = True if request.form.get('status') else False
        task_status = 'completed' if request.form.get('status') else 'not completed'

        try:

            specific_task.status = complete_boolean

        except:

            flash("Something went wrong.", "error")
            return redirect(url_for('todo.index'))

        else:

            db.session.commit()

            flash(f'Task {specific_task.task} has been marked as {task_status}.', 'message')
            return redirect(url_for('todo.index'))

    return render_template('task.html', user_task=specific_task)

@bp.route('/delete/<task_id>/', methods=['GET'])
def delete(task_id):

    '''Delete specific task'''

    try:

        task_to_delete = Todo.query.get(int(task_id))

    except:

        flash("Something went wrong.", "error")
        return redirect(url_for('todo.index'))

    try:

        db.session.delete(task_to_delete)

    except:

        flash("Something went wrong.", "error")
        return redirect(url_for('todo.index'))

    else:

        db.session.commit()

        flash(f'Task {task_to_delete.task} has been deleted.', 'message')
        return redirect(url_for('todo.index'))

app/templates/about.html
{% extends 'base.html' %}

<!-- title -->
{% block title %} About {% endblock %}
<!-- title -->

<!-- app -->
{% block app %}
<!-- navbar -->
{% include 'navbar.html' %}
<!-- navbar -->

<div class="container py-5 app">
  <div class="d-flex align-items-center justify-content-between mb-5">
    <h1>About Todo App</h1>
    <a
      href="https://github.com/LoisaKitakaya/Flask-To-do"
      class="btn btn-dark btn-sm"
      ><i class="bi bi-github"></i> Source code</a
    >
  </div>
  <!-- about content -->
  <div class="card shadow-sm text-bg-light">
    <div class="card-body">
      <p class="mb-3">
        Welcome to <span class="fw-semibold">Todo App</span>. As the name
        suggests, this is an application that helps you record tasks you
        have/want to do. This way you have somewhere where you can reference for
        your planned activities, thus boosting your productivity.
      </p>
      <p class="mb-3">
        <span class="fw-semibold">Todo App</span> is built using
        <a href="https://palletsprojects.com/p/flask/">Flask</a>, a
        <a href="http://python.org/">Python</a> web framework. The Frontend is
        mostly <a href="https://getbootstrap.com/">Bootstrap</a> with some
        little custom styling.
      </p>
      <p class="mb-3">
        The motivation to build this application is actually for personal use.
        But feel free to use it if you want to. There are no ads or promotions
        here. Simply create an account and start enjoying the app.
      </p>
      <p class="mb-3">
        For any suggestions, comments, or complaints, please submit an issue
        <a href="https://github.com/LoisaKitakaya/Flask-To-do/issues">here</a>.
        If you do not have a Github account, you can email me at
        <a href="mailto:kitakayaloisa@gmail.com">kitakayaloisa@gmail.com</a>.
      </p>
      <p class="mb-3">
        Also, if you wish to contribute to this project, you will be pleased
        to know that it is open source. So all you need to do is simply make a
        <a href="https://github.com/LoisaKitakaya/Flask-To-do/pulls"
          >pull request</a
        >
        to the app repository on Github.
      </p>
    </div>
  </div>
  <!-- about content -->
</div>

<!-- footer -->
{% include 'footer.html' %}
<!-- footer -->
{% endblock %}
<!-- app -->

app/templates/addtask.html
<div
  class="modal fade"
  id="addTaskModal"
  tabindex="-1"
  aria-labelledby="addTaskModalLabel"
  aria-hidden="true"
  data-bs-backdrop="static"
  data-bs-keyboard="false"
>
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="addTaskModalLabel">Add Task</h1>
        <button
          type="button"
          class="btn-close"
          data-bs-dismiss="modal"
          aria-label="Close"
        ></button>
      </div>
      <div class="modal-body">
        <form action="/add_task" method="post">
          <div class="mb-3">
            <label for="task" class="form-label">Task name</label>
            <input
              type="text"
              class="form-control"
              name="task"
              placeholder="e.g. Buy new computer tomorrow"
              required
            />
          </div>
          <div class="mb-3">
            <label for="label" class="form-label">Task label</label>
            <select
              class="form-select"
              aria-label="Task labels"
              name="label"
              required
            >
              <option selected>Categorize your task</option>
              <option value="Home">Home</option>
              <option value="Work">Work</option>
              <option value="Social">Social</option>
              <option value="Urgent">Urgent</option>
              <option value="Personal">Personal</option>
            </select>
          </div>
          <div class="mb-3">
            <label for="description" class="form-label">Task description</label>
            <textarea
              class="form-control"
              name="description"
              placeholder="Briefly describe your task"
              required
              rows="3"
            ></textarea>
          </div>
          <div class="mb-3">
            <label for="due_date" class="form-label">Task due date</label>
            <input
              type="datetime-local"
              class="form-control"
              name="due_date"
              required
            />
          </div>
          <div class="mb-3">
            <button type="submit" class="btn btn-success container-fluid">
              <i class="bi bi-calendar2-plus-fill"></i> Add new task
            </button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="shortcut icon"
      href="{{ url_for('static', filename='favicon.ico') }}"
      type="image/x-icon"
    />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65"
      crossorigin="anonymous"
    />
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4"
      crossorigin="anonymous"
    ></script>
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css"
    />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Kanit&family=Poppins&family=Raleway&family=Source+Code+Pro&display=swap"
      rel="stylesheet"
    />
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='style.css') }}"
    />
    <title>{% block title %} {% endblock %} | Todo App</title>
  </head>
  <body>
    <div id="app">
      {% block app %}
      <!--  -->
      {% endblock %}
    </div>
  </body>
  <script src="{{ url_for('static', filename='script.js') }}"></script>
</html>

app/templates/flash.html
{% with messages = get_flashed_messages(with_categories=true) %}
<!--  -->
{% if messages %}
<!--  -->
{% for category, message in messages %}
<!--  -->
{% if category == 'message' %}
<div class="alert alert-success alert-dismissible fade show" role="alert">
  <i class="bi bi-check-circle"></i> {{message}}
  <button
    type="button"
    class="btn-close"
    data-bs-dismiss="alert"
    aria-label="Close"
  ></button>
</div>
{% elif category == 'info' %}
<div class="alert alert-info alert-dismissible fade show" role="alert">
  <i class="bi bi-info-circle"></i> {{message}}
  <button
    type="button"
    class="btn-close"
    data-bs-dismiss="alert"
    aria-label="Close"
  ></button>
</div>
{% elif category == 'warning' %}
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <i class="bi bi-exclamation-circle"></i> {{message}}
  <button
    type="button"
    class="btn-close"
    data-bs-dismiss="alert"
    aria-label="Close"
  ></button>
</div>
{% elif category == 'error' %}
<div class="alert alert-danger alert-dismissible fade show" role="alert">
  <i class="bi bi-x-circle"></i> {{message}}
  <button
    type="button"
    class="btn-close"
    data-bs-dismiss="alert"
    aria-label="Close"
  ></button>
</div>
{% endif %}
<!--  -->
{% endfor %}
<!--  -->
{% endif %}
<!--  -->
{% endwith %}

app/templates/footer.html
<footer class="bg-light border-top">
  <div class="container py-5">
    <p class="text-center">
      Made with <i class="bi bi-suit-heart-fill text-danger"></i> by
      <a href="https://freedomloisa.netlify.app/">Freedom Loisa</a>
    </p>
  </div>
</footer>

app/templates/index.html
{% extends 'base.html' %}

<!-- title -->
{% block title %} Home {% endblock %}
<!-- title -->

<!-- app -->
{% block app %}
<!-- navbar -->
{% include 'navbar.html' %}
<!-- navbar -->

<div class="container py-5 app">
  <!-- flash -->
  <div class="mb-3">{% include 'flash.html' %}</div>
  <!-- flash -->
  <div class="d-flex align-items-center justify-content-between mb-5">
    <h1>Your Todo List</h1>
    <button
      class="btn btn-primary btn-sm"
      data-bs-toggle="modal"
      data-bs-target="#addTaskModal"
    >
      <i class="bi bi-calendar2-plus-fill"></i> Add task
    </button>
  </div>
  <!-- table -->
  {% include 'table.html' %}
  <!-- table -->
</div>

<!-- add task modal -->
{% include 'addtask.html' %}
<!-- add task modal -->

<!-- footer -->
{% include 'footer.html' %}
<!-- footer -->
{% endblock %}
<!-- app -->

app/templates/login.html
{% extends 'base.html' %}

<!-- title -->
{% block title %} Login {% endblock %}
<!-- title -->

<!-- app -->
{% block app %}
<div class="app py-5 container">
  <!-- flash -->
  {% include 'flash.html' %}
  <!-- flash -->
  <div class="card text-bg-light mt-5 mb-3 w-50 mx-auto shadow-sm">
    <div class="card-body">
      <h3 class="text-center mb-3">Login to your account</h3>
      <hr class="mx-3" />
      <form action="/login" method="post" class="mx-3">
        <div class="mb-3">
          <label for="username" class="form-label">Username</label>
          <input
            type="text"
            class="form-control"
            name="username"
            placeholder="e.g. johndoe"
            required
          />
        </div>
        <div class="mb-3">
          <label for="password" class="form-label">Password</label>
          <input
            type="password"
            class="form-control"
            name="password"
            placeholder="************"
            required
          />
        </div>
        <div class="mb-3">
          <button type="submit" class="btn btn-success container-fluid">
            Login
          </button>
        </div>
      </form>
      <hr class="mx-3" />
    </div>
  </div>
  <p class="text-center">
    Don't have an account? <a href="{{ url_for('todo.signup') }}">Signup</a> for
    one.
  </p>
</div>
{% endblock %}
<!-- app -->

app/templates/navbar.html
<nav class="navbar navbar-expand-lg bg-light border-bottom">
  <div class="container">
    <a
      class="navbar-brand"
      href="{{ url_for('todo.index') }}"
      onmouseenter="hoverState()"
      onmouseleave="hoverStateReverse()"
      id="page-banner"
    >
      <i class="bi bi-card-checklist"></i>
      Todo App
    </a>
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarText"
      aria-controls="navbarText"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse pt-1" id="navbarText">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('todo.about') }}">About</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('todo.logout') }}">Logout</a>
        </li>
      </ul>
      <span class="navbar-text"
        >Welcome,
        <span
          class="text-success fw-semibold font-kanit"
          >{{current_user.username}}</span
        ></span
      >
    </div>
  </div>
</nav>

app/templates/signup.html
{% extends 'base.html' %}

<!-- title -->
{% block title %} Signup {% endblock %}
<!-- title -->

<!-- app -->
{% block app %}
<div class="app py-5 container">
  <!-- flash -->
  {% include 'flash.html' %}
  <!-- flash -->
  <div class="card text-bg-light mt-5 mb-3 w-50 mx-auto shadow-sm">
    <div class="card-body">
      <h3 class="text-center mb-3">Create a user account</h3>
      <hr class="mx-3" />
      <form action="/signup" method="post" class="mx-3">
        <div class="mb-3">
          <label for="username" class="form-label">Username</label>
          <input
            type="text"
            class="form-control"
            name="username"
            placeholder="e.g. johndoe"
            required
          />
        </div>
        <div class="mb-3">
          <label for="email" class="form-label">Email address</label>
          <input
            type="email"
            class="form-control"
            name="email"
            placeholder="e.g. name@example.com"
            required
          />
        </div>
        <div class="mb-3">
          <label for="password_one" class="form-label">Password</label>
          <input
            type="password"
            class="form-control"
            name="password_one"
            placeholder="************"
            required
          />
        </div>
        <div class="mb-3">
          <label for="password_two" class="form-label">Confirm password</label>
          <input
            type="password"
            class="form-control"
            name="password_two"
            placeholder="************"
            required
          />
        </div>
        <div class="mb-3">
          <button type="submit" class="btn btn-success container-fluid">
            Signup
          </button>
        </div>
      </form>
      <hr class="mx-3" />
    </div>
  </div>
  <p class="text-center">
    Already have an account?
    <a href="{{ url_for('todo.login') }}">Login</a> here.
  </p>
</div>
{% endblock %}
<!-- app -->

app/templates/table.html
<div class="table-responsive">
  {% if user_tasks %}
  <table class="table table-light table-hover shadow-sm">
    <thead class="table-dark">
      <tr>
        <th scope="col" class="table-number">#</th>
        <th scope="col">Task</th>
        <th scope="col" class="table-header">Label</th>
        <th scope="col" class="table-header">Complete</th>
        <th scope="col" class="table-btn my-btn">Delete</th>
      </tr>
    </thead>
    <tbody class="table-group-divider">
      {% for task in user_tasks %}
      <tr>
        <th scope="row">{{loop.index}}</th>
        <td>
          <a href="{{ url_for('todo.task', task_id=task.id) }}"
            >{{ task.task }}</a
          >
        </td>
        <td class="table-header">
          {% if task.label == 'Home' %}
          <span class="rounded bg-home">{{ task.label }}</span>
          {% elif task.label == 'Work' %}
          <span class="rounded bg-work">{{ task.label }}</span>
          {% elif task.label == 'Social' %}
          <span class="rounded bg-social">{{ task.label }}</span>
          {% elif task.label == 'Urgent' %}
          <span class="rounded bg-urgent">{{ task.label }}</span>
          {% elif task.label == 'Personal' %}
          <span class="rounded bg-personal">{{ task.label }}</span>
          {% endif %}
        </td>
        <td class="table-header">
          {% if task.status == False %}
          <i class="bi bi-x-circle-fill text-warning"></i>
          {% elif task.status == True %}
          <i class="bi bi-check-circle-fill text-success"></i>
          {% endif %}
        </td>
        <td class="table-btn my-btn">
          <a href="{{ url_for('todo.delete', task_id=task.id) }}"
            ><i class="bi bi-trash text-danger"></i
          ></a>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  {% else %}
  <table class="table table-light table-hover shadow-sm">
    <caption>
      It feels very empty over here... Add a new task.
    </caption>
    <thead class="table-dark">
      <tr>
        <th scope="col" class="table-number">#</th>
        <th scope="col">Task</th>
        <th scope="col" class="table-header">Label</th>
        <th scope="col" class="table-header">Complete</th>
        <th scope="col" class="table-btn my-btn">Delete</th>
      </tr>
    </thead>
    <tbody class="table-group-divider">
      <tr>
        <th scope="row"></th>
        <td></td>
        <td class="table-header"></td>
        <td class="table-header"></td>
        <td class="table-btn my-btn"></td>
      </tr>
    </tbody>
  </table>
  {% endif %}
</div>

app/templates/task.html
{% extends 'base.html' %}

<!-- title -->
{% block title %} {{user_task.task}} {% endblock %}
<!-- title -->

<!-- app -->
{% block app %}
<!-- navbar -->
{% include 'navbar.html' %}
<!-- navbar -->

<div class="container py-5 app">
  <div class="d-flex align-items-center justify-content-between mb-5">
    <h1>Your Task</h1>
    <button class="btn btn-secondary btn-sm" onclick="window.history.back()">
      <i class="bi bi-arrow-left-short"></i> Go back
    </button>
  </div>
  <!-- task -->
  <div class="card shadow-sm">
    <div class="card-body">
      <h4><span class="fw-semibold">Task:</span> {{ user_task.task }}</h4>
      <hr class="my-3" />
      <h4 class="mb-3">
        <span class="fw-semibold">Description:</span> {{ user_task.description
        }}
      </h4>
      <h4>
        <span class="fw-semibold">Due:</span>
        <span class="fst-italic">{{ user_task.due_date }}</span>
      </h4>
      <hr class="my-3" />
      <div class="mb-3">
        {% if user_task.label == 'Home' %}
        <p>
          <span class="fw-semibold">Label:</span>
          <span class="rounded bg-home">{{ user_task.label }}</span>
        </p>
        {% elif user_task.label == 'Work' %}
        <p>
          <span class="fw-semibold">Label:</span>
          <span class="rounded bg-work">{{ user_task.label }}</span>
        </p>
        {% elif user_task.label == 'Social' %}
        <p>
          <span class="fw-semibold">Label:</span>
          <span class="rounded bg-social">{{ user_task.label }}</span>
        </p>
        {% elif user_task.label == 'Urgent' %}
        <p>
          <span class="fw-semibold">Label:</span>
          <span class="rounded bg-urgent">{{ user_task.label }}</span>
        </p>
        {% elif user_task.label == 'Personal' %}
        <p>
          <span class="fw-semibold">Label:</span>
          <span class="rounded bg-personal">{{ user_task.label }}</span>
        </p>
        {% endif %}
      </div>
      <div>
        {% if user_task.status == False %}
        <p>
          <span class="fw-semibold">Completed:</span>
          <span class="rounded px-1"
            >{{ user_task.status }}
            <i class="bi bi-x-circle-fill text-warning"></i
          ></span>
        </p>
        {% elif user_task.status == True %}
        <p>
          <span class="fw-semibold">Completed:</span>
          <span class="rounded px-1"
            >{{ user_task.status }}
            <i class="bi bi-check-circle-fill text-success"></i
          ></span>
        </p>
        {% endif %}
      </div>
      <hr class="my-3" />
      <form
        action="{{ url_for('todo.task', task_id=user_task.id) }}"
        method="post"
        class="rounded bg-light shadow-sm p-3"
        id="complete-form"
      >
        <div class="form-check form-switch">
          {% if user_task.status == False %}
          <input
            class="form-check-input"
            type="checkbox"
            role="switch"
            name="status"
            onclick="setComplete()"
          />
          <label class="form-check-label fw-semibold" for="status"
            >Mark task as completed</label
          >
          {% elif user_task.status == True %}
          <input
            class="form-check-input"
            type="checkbox"
            role="switch"
            name="status"
            onclick="setComplete()"
            checked
          />
          <label class="form-check-label fw-semibold" for="status"
            >Mark task as not completed</label
          >
          {% endif %}
        </div>
      </form>
    </div>
  </div>
  <!-- task -->
</div>

<!-- footer -->
{% include 'footer.html' %}
<!-- footer -->
{% endblock %}
<!-- app -->